#!/bin/sh
#
# An example hook script to check the commit log message.
# Called by "git commit" with one argument, the name of the file
# that has the commit message.  The hook should exit with non-zero
# status after issuing an appropriate message if it wants to stop the
# commit.  The hook is allowed to edit the commit message file.
#
# To enable this hook, rename this file to "commit-msg".

# Uncomment the below to add a Signed-off-by line to the message.
# Doing this in a hook is a bad idea in general, but the prepare-commit-msg
# hook is more suited to it.
#
# SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
# grep -qs "^$SOB" "$1" || echo "$SOB" >> "$1"

#
# This example tests that the commit message contains DS, exit 1 will fail the commit.
test "" != "$(grep '\(HSA\|GITR\|AQ\|LINT\|DEVOPS\|NIN\|DP360\|GA\|HDFCBANK\|HEAL\|HIT\|INSIGHTS\|INT\|ISF\|LEAD\|LS\|MIN\|M20\|MP\|MOTOR\|MF\|NET\|PM\|PS\|PI\|QA\|REN\|SDO\|M30\|SMF\|SCS\|C3\|LI20\|MV\|SV\|SLP\|SP\|SS\|MIS\|DS\)-[0-9]\+' "$1")" || {
  echo >&2 "ERROR: Commit message is missing Jira issue number."
  exit 1
}

